#!/usr/bin/env python
from random import sample
from string import ascii_uppercase
from key_value_server.client import Client

client = Client('0.0.0.0', 5555)

print('\nDEMO RESULT STORE ----------------------', client.store(f'key{"".join(sample(ascii_uppercase, 8))}', 'valueRANDOM'), '\n')
print('\nDEMO RESULT STORE ----------------------', client.store('keyA', 'valueA'), '\n')
print('\nDEMO RESULT STORE ----------------------', client.store('keyA', 'valueB'), '\n')
print('\nDEMO RESULT RETRIEVE -------------------', client.retrieve('keyA'), '\n')
print('\nDEMO RESULT RETRIEVE -------------------', client.retrieve('keyC'), '\n')
print('\nDEMO RESULT FIND -----------------------', client.find('vvv'), '\n')
print('\nDEMO RESULT FIND -----------------------', client.find('val'), '\n')
